// export const Commands = {
//     CREATE_USER: "CREATE_USER",
//     GET_USER: "GET_USER",
// }
// export default Commands;

export enum Commands {
    CREATE_USER = "CREATE_USER",
    LOGIN_USER = "LOGIN_USER",
    AUTO_SIGNING = "AUTO_SIGNING",
    LOGOUT = "LOGOUT",
    HARD_LOGOUT = "HARD_LOGOUT",
    BROADCAST_TO_ALL = "BROADCAST_TO_ALL",
    BROADCAST_TO_ALL_EXCEPT_SENDER = "BROADCAST_TO_ALL_EXCEPT_SENDER",
    SELF_EXECUTE = "SELF_EXECUTE",
    GET_USERS_PANEL = "GET_USERS_PANEL",
}